name: AMapGenerator
main: pl.toxicproject.generator.Main
version: 1.0
commands:
  generate:
    description: Generate a map.
    permission: parkour.command.generate
    permission-message: You don't have permission to use this command.